---
apiVersion: core.gardener.cloud/v1
kind: ControllerDeployment
metadata:
  name: provider-dns-cloudflare
helm:
  ociRepository:
    repository: ghcr.io/schrodit/gardener-extension-provider-dns-cloudflare/helm/controller
    tag: latest
  values:
    image:
      tag: 0.2.0
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: provider-dns-cloudflare
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: provider-dns-cloudflare
  resources:
  - kind: DNSRecord
    type: cloudflare-dns
