version: 2

builds:
  - main: ./cmd
    binary: gardener-extension-provider-dns-cloudflare
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
