name: publish
description: 'Publish docker images and helm chart'

inputs:
    ghcr_token:
      description: 'Github token to access the ghcr registry'
      required: true

runs:
    using: 'composite'
    steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Helm
      id: helm
      uses: azure/setup-helm@v4.3.0

    - name: Login to Github Packages
      uses: docker/login-action@v3
      if: inputs.ghcr_token
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}

    - name: Set Version
      shell: bash
      run: echo "version=$(jq -r '.version' ./dist/metadata.json)" >> $GITHUB_OUTPUT
      id: version

    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v6
      with:
        push: true
        target: gardener-extension-provider-dns-cloudflare
        context: ./
        # Note: tags has to be all lower-case
        tags: |
          ghcr.io/schrodit/gardener-extension-provider-dns-cloudflare:${{ steps.version.outputs.version }}

    - name: Archive and push Helm Chart to GitHub Container Registry
      shell: bash
      run: |
        helm package ./charts/controller --version=${{ steps.version.outputs.version }} -d ./dist/helm/controller
        helm push ./dist/helm/controller/gardener-extension-provider-dns-cloudflare-${{ steps.version.outputs.version }}.tgz  oci://ghcr.io/schrodit/helm