apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
{{-  if .Values.ignoreResources }}
  annotations:
    resources.gardener.cloud/ignore: "true"
{{- end }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
      maxSurge: {{ .Values.maxSurge }}
  template:
    metadata:
      annotations:
        {{- if .Values.imageVectorOverwrite }}
        checksum/configmap-gcp-imagevector-overwrite: {{ include (print $.Template.BasePath "/configmap-imagevector-overwrite.yaml") . | sha256sum }}
        {{- end }}
        checksum/configmap-{{ include "name" . }}-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        networking.gardener.cloud/to-runtime-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
{{ include "labels" . | indent 8 }}
    spec:
      priorityClassName: {{ include "name" . }}
      serviceAccountName: {{ include "name" . }}
      containers:
      - name: {{ include "name" . }}
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-provider-dns-cloudflare
        - --config-file=/etc/{{ include "name" . }}/config/config.yaml
        - --dnsrecord-max-concurrent-reconciles={{ .Values.controllers.dnsrecord.concurrentSyncs }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --health-bind-address=:{{ .Values.healthPort }}
        {{- if .Values.gardener.version }}
        - --gardener-version={{ .Values.gardener.version }}
        {{- end }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.imageVectorOverwrite }}
        - name: IMAGEVECTOR_OVERWRITE
          value: /charts_overwrite/images_overwrite.yaml
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 5
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/{{ include "name" . }}/config
        {{- if .Values.imageVectorOverwrite }}
        - name: imagevector-overwrite
          mountPath: /charts_overwrite/
          readOnly: true
        {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: {{ include "labels.app.key" . }}
                operator: In
                values:
                - {{ include "labels.app.value" . }}
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: config
        configMap:
          name: {{ include "name" . }}-configmap
          defaultMode: 420
      {{- if .Values.imageVectorOverwrite }}
      - name: imagevector-overwrite
        configMap:
          name: {{ include "name" . }}-imagevector-overwrite
          defaultMode: 420
      {{- end }}
